### ISSUE TITLE
When can we make this available via the FreeCAD-addons repo

### ISSUE THREAD

**Issue by luzpaz** [podestplatz/BCF-Plugin-FreeCAD#1]

**Comment by podestplatz** [comment]
I am planning to release the final GSoC'19 version today. By then we should be able to push it to the addons repo. 
Just to make sure: Apart from the FCMacro file in the root directory of the repo, nothing else is required by the addons manager right?

**Comment by luzpaz** [comment]
@yorikvanhavre care to weigh in on how we should go about doing this?

**Comment by yorikvanhavre** [comment]
> Apart from the FCMacro file in the root directory of the repo, nothing else is required by the addons manager right?

Right! I think your plugin is ready, the macro will be picked and installed automatically. Tell me when you are ready for launch, and I'll add it

**Comment by podestplatz** [comment]
If you think so, let's go for it then :D


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luzpaz** [comment]
Sweet. I'll close this issue then?

**Comment by podestplatz** [comment]
Yeah sounds good. Purely out of interest: with github issues who is normally considered the one responsible for closing them? 
Till now I didn't use github issues very much ^^

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luzpaz** [comment]
The repo admin or the user who opened them

**Comment by luzpaz** [comment]
If you submit a PR and type Closes #{number} then this will trigger a auto closing on of ticket #{number} in the github issue queue.

**Comment by luzpaz** [comment]
So... go ahead and close this issue :smile:

**Comment by podestplatz** [comment]
Thanks for the explanation :)

**Comment by yorikvanhavre** [comment]
Done! https://github.com/FreeCAD/FreeCAD-addons/commit/7e6307d581137f64c6d0df077c80a1b5752f5233

**Comment by luzpaz** [comment]
Nice! Oh BTW, @yorikvanhavre does this need a logo ?

**Comment by yorikvanhavre** [comment]
That would be good. Probably there is an official BCF logo somewhere that we can use...

**Comment by podestplatz** [comment]
Second thing on my to-do list for tomorrow!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
