### ISSUE TITLE
Add Workbench logo to the AddonManager GUI

### ISSUE THREAD

**Issue by luzpaz** [podestplatz/BCF-Plugin-FreeCAD#2]
Upstream PR: https://github.com/FreeCAD/FreeCAD/pull/2470

**Comment by luzpaz** [comment]
Merged upstream in https://github.com/FreeCAD/FreeCAD/commit/0641ca0d1e020d18f23d2adb49959195266f04f7

**Comment by luzpaz** [comment]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by podestplatz** [comment]
> Merged upstream in [FreeCAD/FreeCAD@0641ca0](https://github.com/FreeCAD/FreeCAD/commit/0641ca0d1e020d18f23d2adb49959195266f04f7)

@luzpaz thank you for adding the icon to the official FreeCAD repository!
